import { X, Search, Plus, SlidersHorizontal, MoreHorizontal, ArrowUpRight, CarFront } from 'lucide-react'

export const money = value => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(value)
export function Badge({ children, tone }) { return <span className={`badge ${tone || String(children).toLowerCase().replaceAll(' ', '-')}`}>{children}</span> }
export function PageHeader({ eyebrow, title, description, action }) { return <div className="page-header"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1>{description && <p className="description">{description}</p>}</div>{action}</div> }
export function SearchFilter({ value, onChange, placeholder = 'Search...' }) { return <div className="controls"><label className="search"><Search size={18}/><input value={value} onChange={e => onChange(e.target.value)} placeholder={placeholder}/></label><button className="button secondary"><SlidersHorizontal size={17}/>Filters</button></div> }
export function EmptyState({ title = 'Nothing here yet', detail = 'New records will appear here once they are added.' }) { return <div className="empty"><CarFront size={30}/><h3>{title}</h3><p>{detail}</p></div> }
export function Modal({ title, children, onClose }) { return <div className="modal-backdrop" onMouseDown={onClose}><section className="modal" onMouseDown={e => e.stopPropagation()}><div className="modal-head"><h2>{title}</h2><button className="icon-button" onClick={onClose} aria-label="Close"><X size={20}/></button></div>{children}</section></div> }
export function MetricCard({ label, value, change, icon: Icon, dark, onClick }) { return <article className={`metric ${dark ? 'metric-dark' : ''} ${onClick ? 'metric-clickable' : ''}`} onClick={onClick} role={onClick ? 'button' : undefined} tabIndex={onClick ? 0 : undefined} onKeyDown={event => { if (onClick && (event.key === 'Enter' || event.key === ' ')) onClick() }}><div className="metric-icon"><Icon size={21}/></div><p>{label}</p><h2>{value}</h2><span className="metric-change"><ArrowUpRight size={15}/>{change}</span></article> }
export function VehicleCard({ vehicle, onSelect }) { return <article className="vehicle-card" onClick={() => onSelect(vehicle)}><div className="vehicle-image"><img src={vehicle.image} alt={vehicle.name}/><Badge>{vehicle.status}</Badge></div><div className="vehicle-card-body"><div><p>{vehicle.year} · {vehicle.type}</p><h3>{vehicle.name}</h3></div><strong>{money(vehicle.price)}</strong><div className="vehicle-meta"><span>{vehicle.mileage}</span><span>{vehicle.fuel}</span><button className="icon-button small" aria-label="Vehicle options" onClick={e => e.stopPropagation()}><MoreHorizontal size={19}/></button></div></div></article> }
export function AddButton({ children, onClick }) { return <button className="button primary" onClick={onClick}><Plus size={18}/>{children}</button> }
